### ISSUE TITLE
Internal Server Error that doesn’t allow the name change

### ISSUE THREAD

**Issue by dsjen** [mediacloud/web-tools#1954]
@titinfoundation reports that the following throw an internal server error when changing the name.  

- http://townhall.com
- http://arstechnica.com 
- http://gq.com/ 
- http://www.msnbc.com/#superglue 

@titinfoundation, I modified https://sources.mediacloud.org/#/sources/19763/edit and changed the name back successfully. Can you confirm that this is a problem and if it is, can you provide some link/details/steps?

**Comment by titinfoundation** [comment]
<img width="1161" alt="Screen Shot 2020-08-07 at 1 58 27 PM" src="https://user-images.githubusercontent.com/64150394/89674429-1cf9c580-d8b6-11ea-9b68-398f8bbf6bf7.png">
This is what happens with GQ for example

**Comment by titinfoundation** [comment]
<img width="1265" alt="Screen Shot 2020-08-07 at 2 00 15 PM" src="https://user-images.githubusercontent.com/64150394/89674551-5a5e5300-d8b6-11ea-8019-59501b33de71.png">
Same with Ars Tecnica

**Comment by dsjen** [comment]
@titinfoundation -- it looks like the problem is that sources with these names already exist. For example, Ars Technica also exists at https://sources.mediacloud.org/#/sources/5813. The system doesn't allow for two sources with the same names to exist.

Do you have a process for reconciling these cases?

**Comment by dsjen** [comment]
@titinfoundation -- just anted to check in. Were you able to reconcile the duplicate names?

**Comment by titinfoundation** [comment]
The reconciliation is not posible because these are publications that have like subsidiaries. Like GQ Australia GQ London so I just let those be.
