### ISSUE TITLE
topic created without media source in solr query

### ISSUE THREAD

**Issue by hroberts** [mediacloud/web-tools#1979]
Someone managed to create a topic without a media source. This will cause the topic to fail with a confusing message when the spider is run, so we should try to catch it during the topic queries creation process.

example:

https://topics.mediacloud.org/#/topics/4506/platforms/manage?focusId&snapshotId=5547&timespanId

**Comment by dsjen** [comment]
I'm not sure how this happened! I created a new topic to try to recreate this, but the UI thwarts me every time. I think it's possible that this was possibly fixed when Cindy refactored the Media Picker.

I'm going to close this issue unless you see it happening in more topics--just open it, and I'll try more creative ways of getting in this state.
