### ISSUE TITLE
Unable to download some CSVs

### ISSUE THREAD

**Issue by dsjen** [mediacloud/web-tools#1995]
When downloading all story counts over time CSV:

[Example query](https://explorer.mediacloud.org/#/queries/search?qs=%5B%7B%22label%22%3A%22((%5C%22virtual%20dating%5C%22%20OR%20%5C%22vide...%22%2C%22q%22%3A%22((%5C%22virtual%20dating%5C%22%20OR%20%5C%22video%20dating%5C%22%20OR%20%5C%22virtual%20dates%5C%22%20OR%20%5C%22video%20dates%5C%22%20OR%20%5C%22virtual%20date%5C%22%20OR%20%5C%22video%20date%5C%22%20OR%20%5C%22online%20dating%5C%22%20OR%20%5C%22dating%20apps%5C%22%20OR%20%5C%22dating%20app%5C%22)%20NOT%20(%5C%22derry%20girls%5C%22%20OR%20%5C%22waldo%20moment%5C%22%20OR%20%5C%22tiger%20king%5C%22))%22%2C%22color%22%3A%22%231f77b4%22%2C%22startDate%22%3A%222019-01-01%22%2C%22endDate%22%3A%222020-07-31%22%2C%22sources%22%3A%5B%5D%2C%22collections%22%3A%5B58722749%2C34412234%2C38379429%2C186572516%5D%2C%22searches%22%3A%5B%5D%7D%2C%7B%22label%22%3A%22((%5C%22virtual%20dating%5C%22%20OR%20%5C%22vide...%22%2C%22q%22%3A%22((%5C%22virtual%20dating%5C%22%20OR%20%5C%22video%20dating%5C%22%20OR%20%5C%22virtual%20dates%5C%22%20OR%20%5C%22video%20dates%5C%22%20OR%20%5C%22virtual%20date%5C%22%20OR%20%5C%22video%20date%5C%22%20OR%20%5C%22online%20dating%5C%22%20OR%20%5C%22dating%20apps%5C%22%20OR%20%5C%22dating%20app%5C%22)%20NOT%20(%5C%22derry%20girls%5C%22%20OR%20%5C%22waldo%20moment%5C%22%20OR%20%5C%22tiger%20king%5C%22))%20AND%20(facebook)%22%2C%22color%22%3A%22%232ca02c%22%2C%22startDate%22%3A%222019-01-01%22%2C%22endDate%22%3A%222020-07-31%22%2C%22sources%22%3A%5B%5D%2C%22collections%22%3A%5B58722749%2C34412234%2C38379429%2C186572516%5D%2C%22searches%22%3A%5B%5D%7D%2C%7B%22label%22%3A%22((%5C%22virtual%20dating%5C%22%20OR%20%5C%22vide...%22%2C%22q%22%3A%22((%5C%22virtual%20dating%5C%22%20OR%20%5C%22video%20dating%5C%22%20OR%20%5C%22virtual%20dates%5C%22%20OR%20%5C%22video%20dates%5C%22%20OR%20%5C%22virtual%20date%5C%22%20OR%20%5C%22video%20date%5C%22%20OR%20%5C%22online%20dating%5C%22%20OR%20%5C%22dating%20apps%5C%22%20OR%20%5C%22dating%20app%5C%22)%20NOT%20(%5C%22derry%20girls%5C%22%20OR%20%5C%22waldo%20moment%5C%22%20OR%20%5C%22tiger%20king%5C%22))%20AND%20(facebook%20AND%20(secur*%20OR%20hack*%20OR%20breach*%20OR%20expos*))%22%2C%22color%22%3A%22%23ff7f0e%22%2C%22startDate%22%3A%222019-01-01%22%2C%22endDate%22%3A%222020-07-31%22%2C%22sources%22%3A%5B%5D%2C%22collections%22%3A%5B58722749%2C34412234%2C38379429%2C186572516%5D%2C%22searches%22%3A%5B%5D%7D%5D)

Console error:
```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'LeafChunk'
    |     property 'lines' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Line'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at postToCombinedDownloadUrl (app_js.0ac65ef5.js:4314)
    at QueryAttentionOverTimeResultsContainer.downloadAllQueriesCsv (app_js.0ac65ef5.js:130633)
    at onClick (app_js.0ac65ef5.js:130704)
    at Object.ba (app_js.0ac65ef5.js:160591)
    at ja (app_js.0ac65ef5.js:160591)
    at ka (app_js.0ac65ef5.js:160591)
    at oa (app_js.0ac65ef5.js:160592)
    at lc (app_js.0ac65ef5.js:160629)
    at jc (app_js.0ac65ef5.js:160628)
    at mc (app_js.0ac65ef5.js:160629)
    at sc (app_js.0ac65ef5.js:160633)
    at Ia (app_js.0ac65ef5.js:160864)
    at Ma (app_js.0ac65ef5.js:160596)
    at Rc (app_js.0ac65ef5.js:160647)
    at id (app_js.0ac65ef5.js:160646)
    at exports.unstable_runWithPriority (app_js.0ac65ef5.js:160907)
    at cg (app_js.0ac65ef5.js:160699)
    at Ga (app_js.0ac65ef5.js:160864)
    at gd (app_js.0ac65ef5.js:160645)
    at HTMLDocument.wrapped (app_js.0ac65ef5.js:164062)
```

**Comment by deblnia** [comment]
Something about the formatting of the filenames!

**Comment by dsjen** [comment]
I tried to recreate this (followed the link, renamed a bunch of queries with weird characters) to no avail. I'll close it and we can reopen if it reemerges.
