### ISSUE TITLE
CSV data upload in Topics throws errors but works with enough refreshes

### ISSUE THREAD

**Issue by ebndulue** [mediacloud/web-tools#1996]
Trying to upload social media data CSV into a topic, I get "Can't Load the Data" errors repeatedly but if I click "Try Again" enough times, it eventually works.

**Comment by dsjen** [comment]
I've been trying to recreate this and it always works for me (both locally and on our production system)! I'm going to close this for now and we can reopen if it becomes an issue down the line.
