### ISSUE TITLE
Add Help text for Verified Twitter Platform

### ISSUE THREAD

**Issue by dsjen** [mediacloud/web-tools#2006]
@hroberts / @epenn -- what sort of information does the user need to enter in order pull in tweets from the verified Twitter ingest @epenn is working on? Search terms?

~~Am I right in thinking that this is an admin only feature--unless we enable users to bring their own API keys?~~ It's available to everyone.

**Comment by dsjen** [comment]
This functionality has been built out on the frontend--just needs to be turned on in the backend. We should add some helpful syntax text similar to that in the reddit pushshift platform page.

![Screen Shot 2020-11-30 at 12 01 04 PM](https://user-images.githubusercontent.com/5265058/100639904-c2242800-3303-11eb-876e-0815c7de9128.png)

**Comment by dsjen** [comment]
Tip/Hack: add the following to platforms_manage::_available_platforms to turn on this functionality (locally):

```
    info['info']["topic_platforms_sources_map"].append({
        'platform_description': 'submissions and comments from twitter.com',
        'platform_name': 'twitter',
        'source_description': 'import from the pushshift.io api',
        'source_name': 'pushshift',
        'topic_platforms_id': 2,
        'topic_sources_id': 2
    })
```

**Comment by ShivamBaishkhiyar** [comment]
I want to work on this issue. Hey , would you please help me to set up python in my windows system?
