### ISSUE TITLE
Enable Remove from Next Snapshot?

### ISSUE THREAD

**Issue by dsjen** [mediacloud/web-tools#2013]
A user recently found the "Remove from Next Snapshot" button. @rahulbot -- do you remember if this was this ever implemented? I dug around and didn't see anything to indicate that it was.

![Screen Shot 2020-11-18 at 4 48 53 PM](https://user-images.githubusercontent.com/5265058/99592399-2bc83c00-29be-11eb-8cbf-71fcd6f05cb9.png)

**Comment by hroberts** [comment]
this was something that was in the ugly original hal-version of the topics
ui but never made it into the slick ui.  we would need to add a backend end
point, but it wouldn't be too hard.

-hal

**Comment by dsjen** [comment]
I see! Thanks for the history about that! I'll check to see how useful this would be.
