### ISSUE TITLE
wrong links shown on topic media page

### ISSUE THREAD

**Issue by hroberts** [mediacloud/web-tools#2043]
the results in the inlinks box on the topic media page appear to be wrong.

on this page:

https://topics.mediacloud.org/#/topics/5333/media/24030?focusId&q&snapshotId=6251&timespanId=1244933

there are 20 results displayed as inlinks, but when I make the api call directly:

https://api.mediacloud.org/api/v2/topics/5333/stories/list?link_to_media_id=24030&timespans_id=1244933

I only get 9 results.  When I look directly in the database, I also see the 9 results, and when I look at the underlying topic_links table that generates the snapshot data, I also see the 9 results.

I haven't double checked the outlinks but I suspect they are wrong as well.  the stories list itself seems to be fine.

I vaguely remember this being an issue several months or a year ago, but I thought it had gotten fixed at some point.

**Comment by dsjen** [comment]
Hmm, this is very interesting! It seems like the frontend is calling the API with different parameters. Instead of `link_to_media_id` it's passing in `'q': 'media_id:24030'`.

I can't quite dig in further at this very moment, but will do so in a bit and report back.

**Comment by hroberts** [comment]
that sounds wrong.  the only way to get the in links is to use the
link_to_* parameters.  that information is not stored in solr, so you have
to go through the api parameter.

-hal

**Comment by dsjen** [comment]
@ebndulue -- I want to make sure that you're aware of this issue. It looks like the stories in the media in/out links weren't correct. I'll have a patch for this next week.
