### ISSUE TITLE
Stuck Topic: 5478

### ISSUE THREAD

**Issue by ebndulue** [mediacloud/web-tools#2050]
User reported stuck topic: https://topics.mediacloud.org/#/topics/5478/summary?focusId&snapshotId=6324. Admin view shows not updated in over a week, on 15th spidering iteration. 

***Note, frequently when topics appear stuck they are on the 15th spidering iteration. Not sure if that is relevant information.

**Comment by dsjen** [comment]
This one has failed (too big)
