### ISSUE TITLE
Getting "Can't Load the Data" when trying to upload CSV into platform builder

### ISSUE THREAD

**Issue by ebndulue** [mediacloud/web-tools#2054]
I'm trying to upload a CSV of Tweets, and after I validate the format, I am seeing an error of "Can't Load the Data." Hard refresh doesn't seem to change anything. Attached is the CSV I'm trying to upload. (I had to attach XLSX in GitHub, but it is the same file in CSV that I am using). 

[Kenya_tweets_for_MC_topic.xlsx](https://github.com/mediacloud/web-tools/files/5993033/Kenya_tweets_for_MC_topic.xlsx)

**Comment by dsjen** [comment]
I think there might be a few problems with this. I downloaded the `.xlsx` file and saved it as a `csv`. It ends up adding is a special character to the front of the file, which causes problems for the system.

When I removed that character, I ran into another problem with the format of the dates. The system can only read certain formats of dates and `Jan 29,   2020 @ 05:33:50.000` isn't "valid." When you export the data, do you happen to have the ability to change how the dates are formatted? Something like `2020-01-29` (I suspect even `Jan 29, 2020` would work well. If that's not possible, i can script something up to reformat the dates.

**Comment by dsjen** [comment]
Just so I have a paper trail -- one issue is the way excel exported the CSV. I ended up following the instructions on https://stackoverflow.com/questions/7297888/0xef-0xbb-0xbf-character-showing-up-in-files-how-to-remove-them/15137601#15137601 to remove the BOM characters.

**Comment by ebndulue** [comment]
This data came from the Twitter API originally, was the uploaded into Kibana, and then downloaded to a CSV. Rahul executed the data pull and upload, so I'm not sure if there are options regarding the dates there...

**Comment by dsjen** [comment]
Got it! I'll whip something up to format the csv so you can test out the links.

**Comment by dsjen** [comment]
It turns out the excel had a quick day to format the dates. Instructions at https://support.microsoft.com/en-us/office/split-text-into-different-columns-with-the-convert-text-to-columns-wizard-30b14928-5550-41f5-97ca-7a3e9c363ed7.

Here's a screenshot of what I did:
![Screen Shot 2021-02-18 at 4 46 40 PM](https://user-images.githubusercontent.com/5265058/108427150-b95c3780-720a-11eb-86ce-061bc86f3062.png)

I'll send you the processed CSV separately.
