### ISSUE TITLE
puppeteer

### ISSUE THREAD

**Issue by syedsafi30** [mediacloud/web-tools#2066]
Hi, I am interested in working for the project on Creating a self-contained, browser-based page HTML for Gsoc 2021, I have gone throught the development tasks which are needed to be completed and I have a query regarding creating a chromeless browser, after going through some research I came across puppeteer which could be helpful in creating a headless chrome. I need you to guide me so that I can start contributing as soon as possible and I would know whether I am on the right path towards achieving the goals needed

We strive to be responsive. At the same time, we're small nonprofit and can't always be. Thanks for being patient with us! Please follow our [contributing guidelines](https://github.com/mediacloud/.github/blob/master/CODE_OF_CONDUCT.md).

**Comment by dsjen** [comment]
Hi, please read about our proposal templates at https://summerofcode.withgoogle.com/organizations/6154545979195392/. We'll be able to comment on proposals from there.
