### ISSUE TITLE
Stuck topic #6428

### ISSUE THREAD

**Issue by ebndulue** [mediacloud/web-tools#2081]
My topic hasn't updated in 5 days; seed stories was 30k and I upped limit to 500,000 I think, so it shouldn't be size related. Thanks for looking into this.

**Comment by dsjen** [comment]
This has been restarted and seems to be making progress. Please reopen if it fails!

**Comment by esirK** [comment]
@dsjen how do you restart a topic?

**Comment by dsjen** [comment]
@esirK -- oh, it's a bit of a secret. For admin users, you can go to the topic's version page and then click "quick create & spider." I hope that's helpful! This will put the topic back in queue.

![Screen Shot 2021-05-26 at 9 13 26 AM](https://user-images.githubusercontent.com/5265058/119665746-b02ec800-be02-11eb-90a9-af19a0af0ffd.png)

**Comment by esirK** [comment]
Hey @dsjen  yes this was helpful. Thank you 😊
